;;; company-qml-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-qml.el

(autoload 'company-qml "company-qml" "\
A `company-mode' completion back-end for qml-mode.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-qml" '("company-qml-" "qmltypes-parser-file-list"))


;;; Generated autoloads from qmltypes-parser.el

(register-definition-prefixes "qmltypes-parser" '("qmltypes-parser-"))

;;; End of scraped data

(provide 'company-qml-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-qml-autoloads.el ends here
