;;; caser-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from caser.el

(autoload 'caser-camelcase-dwim "caser" "\
Camelcase words in the region, if active; if not, camelcase word at point.

This converts it from dash-case or snake_case to camelCase.

If the region is active, this function calls `caser-camelcase-region'.
Otherwise, it calls `caser-camelcase-word', with prefix argument passed to it
to camelcase ARG words.

(fn ARG)" t)
(autoload 'caser-snakecase-dwim "caser" "\
Snakecase words in the region, if active; if not, snakecase word at point.

This converts it from camelCase or dash-case to snake_case.

If the region is active, this function calls `caser-snakecase-region'.
Otherwise, it calls `caser-snakecase-word', with prefix argument passed to it
to snakecase ARG words.

(fn ARG)" t)
(autoload 'caser-dashcase-dwim "caser" "\
Dashcase words in the region, if active; if not, dashcase word at point.

This converts it from camelCase or snake_case to dash-case.

If the region is active, this function calls `caser-dashcase-region'.
Otherwise, it calls `caser-dashcase-word', with prefix argument passed to it
to dashcase ARG words.

(fn ARG)" t)
(autoload 'caser-dashcase-from-space-dwim "caser" "\
Dashcase what you mean, including converting spaces to dashes.

If the region is active, dashcase it; otherwise dashcase the word at point.

This converts it from camelCase or snake_case to dash-case.

If the region is active, this function calls `caser-dashcase-region'.
Otherwise, it calls `caser-dashcase-word', with prefix argument passed to it
to dashcase WORDS words.

(fn &optional WORDS)" t)
(autoload 'caser-snakecase-from-space-dwim "caser" "\
Snakecase what you mean, including converting spaces to underscores.

If the region is active, snakecase it; otherwise snakecase WORDS
words at point, defaulting to 1.

This converts it from camelCase or dash-case to snake_case.

(fn &optional WORDS)" t)
(autoload 'caser-camelcase-from-space-dwim "caser" "\
Camelcase what you mean, including converting spaces to underscores.

If the region is active, camelcase it; otherwise camelcase WORDS
words at point, defaulting to 1.

This converts it from snake_case or dash-case to camelCase.

(fn &optional WORDS)" t)
(register-definition-prefixes "caser" '("caser-"))

;;; End of scraped data

(provide 'caser-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; caser-autoloads.el ends here
