;;; ivy-xref-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ivy-xref.el

(autoload 'ivy-xref-show-xrefs "ivy-xref" "\
Show the list of xrefs returned by FETCHER and ALIST via ivy.

(fn FETCHER ALIST)")
(autoload 'ivy-xref-show-defs "ivy-xref" "\
Show the list of definitions returned by FETCHER and ALIST via ivy.
Will jump to the definition if only one is found.

(fn FETCHER ALIST)")
(register-definition-prefixes "ivy-xref" '("ivy-xref-"))

;;; End of scraped data

(provide 'ivy-xref-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ivy-xref-autoloads.el ends here
