;;; flymake-diagnostic-at-point-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-diagnostic-at-point.el

(autoload 'flymake-diagnostic-at-point-set-timer "flymake-diagnostic-at-point" "\
Set the error display timer for the current buffer." t)
(autoload 'flymake-diagnostic-at-point-cancel-timer "flymake-diagnostic-at-point" "\
Cancel the error display timer for the current buffer." t)
(register-definition-prefixes "flymake-diagnostic-at-point" '("flymake-diagnostic-at-point-"))

;;; End of scraped data

(provide 'flymake-diagnostic-at-point-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-diagnostic-at-point-autoloads.el ends here
