;;; sideline-eglot-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sideline-eglot.el

(autoload 'sideline-eglot "sideline-eglot" "\
Eglot backend for sideline.

Argument COMMAND is required in sideline backend.

(fn COMMAND)")
(register-definition-prefixes "sideline-eglot" '("sideline-eglot-"))

;;; End of scraped data

(provide 'sideline-eglot-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sideline-eglot-autoloads.el ends here
