;;; xwwp-follow-link-helm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xwwp-follow-link-helm.el

(register-definition-prefixes "xwwp-follow-link-helm" '("xwwp-follow-link-completion-backend-helm"))

;;; End of scraped data

(provide 'xwwp-follow-link-helm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xwwp-follow-link-helm-autoloads.el ends here
