;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	god-mode-all
	kill-region
	my-quit-god-mode
	ace-select-window
	god-mode-self-insert
	helm-M-x
	iedit-switch-to-mc-mode
	keyboard-escape-quit
	multiple-cursors-menu/mc/mark-all-like-this
	multiple-cursors-menu/mc/mark-next-like-this
	multiple-cursors-menu/mc/mark-previous-like-this
	my-god-char-forward-and-insert-mode
	))

(setq mc/cmds-to-run-once
      '(
	))
